import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

export interface ConsumerWorkflowOptions {
  controlRepository: string;
  controlRef: string;
  policyPath: string;
  nodeVersion?: string;
  installChromium?: boolean;
  attest?: boolean;
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`invalid consumer workflow: ${message}`);
}

export function validateConsumerWorkflowOptions(options: ConsumerWorkflowOptions): void {
  assert(
    /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(options.controlRepository),
    "controlRepository must be owner/repository",
  );
  assert(/^[0-9a-f]{40}$/.test(options.controlRef), "controlRef must be a full lowercase 40-character commit SHA");
  assert(options.policyPath.length > 0 && !options.policyPath.startsWith("/"), "policyPath must be a relative path");
  assert(
    !options.policyPath.split("/").some((segment) => segment === ".." || segment.length === 0),
    "policyPath cannot contain empty or parent-directory segments",
  );
  assert(/^\d+(?:\.\d+){0,2}$/.test(options.nodeVersion ?? "24"), "nodeVersion must be a numeric Node version");
}

export function renderConsumerWorkflow(options: ConsumerWorkflowOptions): string {
  validateConsumerWorkflowOptions(options);
  const nodeVersion = options.nodeVersion ?? "24";

  return `# Generated by delivery-gate init. Keep the workflow and control commit maintainer-owned.
name: Agent Delivery Gate

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  delivery-gate:
    uses: ${options.controlRepository}/.github/workflows/reusable-delivery-gate.yml@${options.controlRef}
    with:
      control-repository: ${JSON.stringify(options.controlRepository)}
      control-ref: ${JSON.stringify(options.controlRef)}
      policy-path: ${JSON.stringify(options.policyPath)}
      node-version: ${JSON.stringify(nodeVersion)}
      install-chromium: ${options.installChromium ?? false}
      attest: ${options.attest ?? false}
    # GitHub validates the reusable workflow's maximum permissions at startup.
    # The pinned workflow explicitly downgrades candidate verification to contents: read.
    permissions:
      contents: read
      id-token: write
      attestations: write
`;
}

export async function writeConsumerWorkflow(
  outputPath: string,
  options: ConsumerWorkflowOptions,
  force = false,
): Promise<string> {
  const absolutePath = resolve(outputPath);
  await mkdir(dirname(absolutePath), { recursive: true });
  await writeFile(absolutePath, renderConsumerWorkflow(options), {
    encoding: "utf8",
    flag: force ? "w" : "wx",
  });
  return absolutePath;
}
